# Tensorflow 2

![title](./img/2.png)

## 其他框架

![001](./img/001.png)

## 2版本跟1.x的对比

- 首先Tensorflow是深度学习框架，定位就是工具，帮助我们完成实验和任务的，所以工具当然是使用起来越简单才是越实用的！

- 2版本并不是难度增大，而是大大简化是建模的方法和步骤，与1.X版本相比更简单实用了，难度更小了！

- 终于把Keras Api当做核心了，使用起来一句话概述就是简单它妈给简单开门。。。

- 跨平台，各种现成模型，eager mode使得调试起来终于不那么难受了！

- 整体感觉就是用起来更接地气了，深度学习入门和进阶最好的方法就是多练习多试验，看论文复现代码和调试的过程我觉得是提升最快的途径！

![title](./img/1.png)

## Tensorflow 2版本安装

### 2.安装Tensorflow: https://tensorflow.google.cn/
- CPU版本安装：pip install tensorflow
- GPU版本安装：pip install tensorflow-gpu 需要配置好CUDA10版本
- 如果安装报错了，那就自己下载一份：https://pypi.org/project/tensorflow-gpu/#files

## 简单试试

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'2.3.0'

In [3]:
# Eager Execution
# 动态图模型
x = [[1.]]
m = tf.matmul(x, x)
print(m)

tf.Tensor([[1.]], shape=(1, 1), dtype=float32)


In [4]:
x = tf.constant([[1,9],[3,6]])
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 9],
       [3, 6]])>

In [5]:
x = tf.add(x, 1)
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2, 10],
       [ 4,  7]])>

### Tensor是什么

tensor 矩阵

flow 流

- 当做是可以进行GPU加速计算的矩阵就可以

![Scalar, vector, matrix, tensor - a drawing by Tai-Danae Bradley](https://uploads-ssl.webflow.com/5b1d427ae0c922e912eda447/5cd99a73f8ce4494ad86852e_arraychart.jpg)

### 转换格式

In [16]:
x.numpy()

array([[ 2, 10],
       [ 4,  7]])

In [21]:
x = tf.cast(x, tf.float32)
x

<tf.Tensor: id=21, shape=(2, 2), dtype=float32, numpy=
array([[ 3., 11.],
       [ 5.,  8.]], dtype=float32)>

In [6]:
x1 = np.ones([2,2])
x2 = tf.multiply(x1, 2)
print(x1)
print(x2)

[[1. 1.]
 [1. 1.]]
tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float64)
