In [7]:
import numpy
numpy.__version__

'1.18.5'

In [16]:
import numpy as np
z=np.zeros((5,5))
print(z.size*z.itemsize)

200


In [20]:
print(help(np.info(np.add)))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [21]:
array=np.arange(10,50,1)
array=array[::-1]
array

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [64]:
np.nonzero([1,2,3,4,5,0,0,0,1321321,123,0])

(array([0, 1, 2, 3, 4, 8, 9], dtype=int64),)

In [33]:
array=np.random.random((3,3))

print(array.min())

print(array.max())

0.05398478533714324
0.6898051626991852


In [40]:
array=np.ones((5,5)) 
array2=np.pad(array,pad_width=1,mode='constant',constant_values=0)
print(array2)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [45]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

In [50]:
array=np.random.random((5,5))
max=array.max()
min=array.min()
array=(array-min)/(max-min)
array

array([[0.14444102, 0.84010993, 0.58570267, 0.66748022, 0.07406578],
       [0.35183234, 0.4457565 , 0.39782898, 0.95484287, 0.74499781],
       [0.02075031, 0.07998829, 0.96880492, 0.54424164, 1.        ],
       [0.68382489, 0.3400838 , 0.        , 0.23074504, 0.03106487],
       [0.95894378, 0.33450782, 0.1342922 , 0.29631393, 0.00717938]])

In [55]:
z1=np.random.randint(0,10,10)
z2=np.random.randint(0,10,10)
print(z1)
print(z2)
print(np.intersect1d(z1,z2))

[4 0 7 0 9 1 2 9 5 6]
[2 0 1 7 0 9 7 4 1 8]
[0 1 2 4 7 9]


In [61]:
yesterday = (date.today() + timedelta(days=-1)).strftime("%Y-%m-%d")
today = (date.today().strftime("%Y-%m-%d"))
tomorrow = (date.today() + timedelta(days=+1)).strftime("%Y-%m-%d")
print(yesterday)
print(today)
print(tomorrow)

2020-09-01
2020-09-02
2020-09-03


In [6]:
import numpy as np
print(np.arange('2020-09','2020-10',dtype='datetime64[D]'))

['2020-09-01' '2020-09-02' '2020-09-03' '2020-09-04' '2020-09-05'
 '2020-09-06' '2020-09-07' '2020-09-08' '2020-09-09' '2020-09-10'
 '2020-09-11' '2020-09-12' '2020-09-13' '2020-09-14' '2020-09-15'
 '2020-09-16' '2020-09-17' '2020-09-18' '2020-09-19' '2020-09-20'
 '2020-09-21' '2020-09-22' '2020-09-23' '2020-09-24' '2020-09-25'
 '2020-09-26' '2020-09-27' '2020-09-28' '2020-09-29' '2020-09-30']


In [12]:
z=np.random.uniform(0,10,10)
print(z)
print(np.floor(z))

[8.37138233 1.38448295 7.10638134 3.45312191 1.65704239 2.06179574
 2.27664058 6.10719995 8.47688914 0.52099571]
[8. 1. 7. 3. 1. 2. 2. 6. 8. 0.]


In [14]:
z=np.zeros(5)
z.flags.writeable=False
z

array([0., 0., 0., 0., 0.])

In [15]:
z=np.zeros(5)
z.flags.writeable=False
z[0]=1
z

ValueError: assignment destination is read-only

In [30]:
np.set_printoptions(threshold=7)
z=np.zeros((20,20))
z

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [35]:
import sys
np.set_printoptions(threshold=sys.maxsize)
a=np.zeros((20,20))
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

In [39]:
a=np.arange(100)
b=np.random.uniform(0,100)
print(b)
index=(np.abs(a-b)).argmin()
print(a[index])

82.35466727435605
82


In [40]:
a=np.arange(10,dtype=np.int32)
print(a.dtype)
a=a.astype(np.float32)
print(a.dtype)

int32
float32


In [49]:
q=np.arange(16).reshape(4,4)
for index,value in np.ndenumerate(q):
    print(index,value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(1, 3) 7
(2, 0) 8
(2, 1) 9
(2, 2) 10
(2, 3) 11
(3, 0) 12
(3, 1) 13
(3, 2) 14
(3, 3) 15


In [81]:
z=np.random.randint(0,10,(3,3))
print(z)
print(z[z[:,1].argsort()])

[[6 7 0]
 [8 0 9]
 [3 8 3]]
[[8 0 9]
 [6 7 0]
 [3 8 3]]


In [102]:
z=np.array([1,1,1,2,2,3,3,4,5,8,])

np.bincount(z)

array([0, 3, 2, 2, 1, 1, 0, 0, 1], dtype=int64)

In [110]:
z=np.random.randint(0,10,(4,4,4,4))
res=z.sum(axis=(-2,-1))
print(res)

[[76 78 93 77]
 [91 74 47 81]
 [64 77 80 64]
 [59 61 67 60]]


In [111]:
z=np.arange(25).reshape(5,5)
print(z)
z[[0,1]]=z[[1,0]]
print(z)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [112]:
z=np.random.randint(0,10,50)
print(z)
print(np.bincount(z).argmax())

[7 5 0 4 6 2 3 5 7 9 4 9 6 6 4 9 4 6 4 2 8 2 5 1 4 2 7 9 1 2 2 5 7 0 0 9 9
 8 0 2 9 0 3 7 1 2 2 7 7 1]
2


In [125]:
z=np.arange(7000)
np.random.shuffle(z)
n=5
print(z[np.argpartition(-z,n)[:n]])

[6997 6999 6996 6998 6995]


In [163]:
np.set_printoptions(threshold=sys.maxsize)
z=np.random.randint(0,2,(10,3))
print(z)
for i in range(10):
    o=z[i]
    if o[0]==o[1]==o[2]:
        continue
    else:
        print(o)

[[1 0 1]
 [0 0 0]
 [0 0 0]
 [1 1 0]
 [0 1 0]
 [1 0 1]
 [0 1 0]
 [0 1 1]
 [1 1 0]
 [1 1 1]]
[1 0 1]
[1 1 0]
[0 1 0]
[1 0 1]
[0 1 0]
[0 1 1]
[1 1 0]
