In [1]:
import numpy as np
print(np.version)

<module 'numpy.version' from 'C:\\Users\\34417\\anaconda3\\lib\\site-packages\\numpy\\version.py'>


In [8]:
z=np.zeros((7,7))

print('%d bytes ' %(z.size*(z.itemsize)))

392 bytes 


In [9]:
print(help(np.info(np.add)))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [10]:
cui_array=np.arange(10,50,1)

cui_array=cui_array[::-1]

cui_array

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [12]:
yu_array = np.arange(5)
np.nonzero(yu_array)
#(array([1, 2, 3, 4]),)

(array([1, 2, 3, 4], dtype=int64),)

In [13]:
yu_array = np.random.random((3,3))
yu_array.min()
yu_array.max()

0.9240525367330745

In [14]:
yu_array = np.ones((5,5))
yu_array = np.pad(yu_array,pad_width=1, mode='constant',constant_values = 0)
yu_array

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [15]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

In [16]:
yu_array = np.random.random((5,5))
yu_max = yu_array.max()
yu_min = yu_array.min()
yu_array = (yu_array-yu_min)/(yu_max-yu_min)
yu_array

array([[0.07528219, 0.09185061, 0.2329245 , 0.40561389, 0.        ],
       [0.29531964, 0.63145062, 0.68860603, 0.25239289, 1.        ],
       [0.15488179, 0.59143206, 0.94217902, 0.10403147, 0.04264525],
       [0.56303831, 0.18528684, 0.01032383, 0.76617052, 0.58009706],
       [0.13230608, 0.97351933, 0.27572871, 0.08642181, 0.17972533]])

In [17]:
yu_array = np.random.randint(0,10,8)
xu_array = np.random.randint(0,10,8)
print(yu_array)
print(xu_array)
np.intersect1d(yu_array,xu_array)

[3 3 4 7 5 3 9 9]
[9 6 0 5 6 5 6 4]


array([4, 5, 9])

In [24]:
today = np.datetime64('today','D')
yesterday  = np.datetime64('today','D')-np.timedelta64('1','D')
tomorrow = np.datetime64('today','D')+np.timedelta64('1','D')
print(yesterday)
print(today)
print(tomorrow)

2020-09-01
2020-09-02
2020-09-03


In [25]:
np.arange('2019-10','2019-11',dtype = 'datetime64[D]')

array(['2019-10-01', '2019-10-02', '2019-10-03', '2019-10-04',
       '2019-10-05', '2019-10-06', '2019-10-07', '2019-10-08',
       '2019-10-09', '2019-10-10', '2019-10-11', '2019-10-12',
       '2019-10-13', '2019-10-14', '2019-10-15', '2019-10-16',
       '2019-10-17', '2019-10-18', '2019-10-19', '2019-10-20',
       '2019-10-21', '2019-10-22', '2019-10-23', '2019-10-24',
       '2019-10-25', '2019-10-26', '2019-10-27', '2019-10-28',
       '2019-10-29', '2019-10-30', '2019-10-31'], dtype='datetime64[D]')

In [26]:
yu_array = np.random.uniform(0,10,10) 
np.floor(yu_array)

array([8., 0., 0., 5., 0., 5., 6., 4., 1., 3.])

In [33]:
z=np.zeros(5)
z.flags.writeable=False
yu_array[0] = 1

ValueError: assignment destination is read-only

In [34]:
import sys
np.set_printoptions(threshold=5) #打印部分
np.set_printoptions(threshold=sys.maxsize) #打印全部
yu_array = np.zeros((15,15))
yu_array

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [35]:
yu_array = np.arange(100)
xu_array = np.random.uniform(0,100) #指定一个随机数
print(xu_array)
index = (np.abs(yu_array-xu_array)).argmin()
print(yu_array[index])

23.067236587528683
23


In [36]:
yu_array = np.arange(10,dtype=np.int32)
yu_array = yu_array.astype(np.float32)
yu_array.dtype

dtype('float32')

In [37]:
yu_array = np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(yu_array):
    print(index,value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [38]:
yu_array = np.random.randint(0,10,(3,3))
print(yu_array)
print(yu_array[yu_array[:,0].argsort()])#第一列

[[9 5 9]
 [5 4 6]
 [6 2 8]]
[[5 4 6]
 [6 2 8]
 [9 5 9]]


In [39]:
yu_array = np.array([1,1,1,2,2,3,3,4,5,8])
np.bincount(yu_array)

array([0, 3, 2, 2, 1, 1, 0, 0, 1], dtype=int64)

In [40]:
yu_array = np.random.randint(0,10,(4,4,4,4))
res = yu_array.sum(axis = (-2,-1))
res

array([[ 59,  66,  78,  74],
       [ 69,  70,  60,  57],
       [ 82,  65,  73,  69],
       [ 94,  70, 101,  75]])

In [41]:
yu_array = np.arange(25).reshape(5,5)
yu_array[:,[0,1]] = yu_array[:,[1,0]]
yu_array[[0,1]] = yu_array[[1,0]]
yu_array

array([[ 6,  5,  7,  8,  9],
       [ 1,  0,  2,  3,  4],
       [11, 10, 12, 13, 14],
       [16, 15, 17, 18, 19],
       [21, 20, 22, 23, 24]])

In [42]:
yu_array = np.random.randint(0,10,5)
print(yu_array)
print(np.bincount(yu_array).argmax())

[1 0 5 1 5]
1


In [43]:
yu_array = np.arange(5000)
np.random.shuffle(yu_array)
k = 5
print(yu_array[np.argpartition(-yu_array,k)[:k]]) 

[4997 4999 4998 4996 4995]


In [46]:
import sys
np.set_printoptions(threshold=sys.maxsize)
yu_array = np.random.randint(0,5,(10,3))
yu_arraym = np.all(yu_array[:,1:] == yu_array[:,:-1],axis = 1)
